// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM546N19tHfnImm_qeJV4X_Bi98rxB11o',
    appId: '1:735766256951:web:9fb3fefcde241734cb4eb2',
    messagingSenderId: '735766256951',
    projectId: 'ungdungdatlichkham',
    authDomain: 'ungdungdatlichkham.firebaseapp.com',
    databaseURL: 'https://ungdungdatlichkham-default-rtdb.firebaseio.com',
    storageBucket: 'ungdungdatlichkham.appspot.com',
    measurementId: 'G-R2M22X231C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5z9jkHrjTrdeXiPy21rjRNka9ThZMPU',
    appId: '1:735766256951:android:c0a7871d0a3012accb4eb2',
    messagingSenderId: '735766256951',
    projectId: 'ungdungdatlichkham',
    databaseURL: 'https://ungdungdatlichkham-default-rtdb.firebaseio.com',
    storageBucket: 'ungdungdatlichkham.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8kHbbFQpBoZOhrAwD_mL4Q4woN9MnxhA',
    appId: '1:735766256951:ios:7a1c7c71fa22594bcb4eb2',
    messagingSenderId: '735766256951',
    projectId: 'ungdungdatlichkham',
    databaseURL: 'https://ungdungdatlichkham-default-rtdb.firebaseio.com',
    storageBucket: 'ungdungdatlichkham.appspot.com',
    iosBundleId: 'com.example.ungdungdatlichkham',
  );
}
